apiVersion: v1
kind: Service
metadata: 
  name: webhubs
  labels:
    name: webhubs-service
    app: website
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    name: webhubs-pod
    app: website